In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import optimize

In [2]:
a = np.array([1,2,3,4,5,6])
a[1]

2

In [3]:
np.zeros(2)

array([0., 0.])

In [4]:
np.ones(3)

array([1., 1., 1.])

In [5]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [6]:
a < 2

array([ True, False, False, False, False, False])

In [7]:
a[a < 3]

array([1, 2])

In [8]:
a % 2

array([1, 0, 1, 0, 1, 0], dtype=int32)

In [9]:
b = np.array([1,2,3,4,5,6], dtype=np.int64)
b

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [10]:
c=np.arange(1,10).reshape(3,3)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
c[1,:]

array([4, 5, 6])

In [12]:
a.sum()

21

sum rows with

In [13]:
c.sum(axis=0)

array([12, 15, 18])

sum columns with

In [14]:
c.sum(axis=1)

array([ 6, 15, 24])

In [15]:
d=np.array([[1,2],[3,4]])
d

array([[1, 2],
       [3, 4]])

In [16]:
d.T

array([[1, 3],
       [2, 4]])

In [19]:
d.transpose()

array([[1, 3],
       [2, 4]])

In [17]:
d.shape

(2, 2)

In [18]:
np.random.randn(10, 4)

array([[-0.22750747, -2.20556796, -0.92556378, -1.24147131],
       [ 0.27456961,  0.96405545,  1.30897248, -0.60117221],
       [-0.92423297,  0.28737104, -1.44900581, -1.6603792 ],
       [-0.01001136,  0.51592319, -0.44182507,  1.0460624 ],
       [-1.21566112,  0.05277987,  0.14473755,  0.16276406],
       [ 2.08998358, -0.6703535 ,  0.74350007,  0.89174345],
       [-0.69337954, -0.06735495, -2.7885286 , -0.05317535],
       [ 1.13138733, -1.53437695, -1.06316927,  0.50875331],
       [ 1.0836368 , -0.56114035,  0.5491282 , -0.0139276 ],
       [-0.58248312,  0.22871877, -1.19419825, -1.1062484 ]])

Remember that 1D arrays are different from matrices in numpy. Always use matrices in order to display vectors.

In [21]:
np.array([[1, 2, 3, 4]]).reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])